= JSON Schema for Clojure(Script)

Almost all Clojure implementations of https://json-schema.org/[json
schema validators] wrap Java libraries. This is generally a good idea.

However, there are some reasons why a _native_ Clojure implementation
can be useful:

* Java libraries compile jsonschema to object graphs, making them
  inaccessible to many of the data functions in the Clojure core
  library.

* On the front-end, it can be painful to have to convert Clojure data
  to JavaScript objects simply for the purposes of calling a
  jsonschema validation such as
  https://github.com/epoberezkin/ajv[Ajv].

* Extensibility: JSON Schema is designed to be extended with additional
  vocabularies. Clojure has some nice open-for-extension mechanisms.

* Size: Implementing JSON Schema is not that scary in a language as
  nice as Clojure. There's not so much code to read, understand and
  possibly extend.

== Scope

This library implements JSON Schema 'draft7'
(draft-handrews-json-schema-validation-01).

== Status

CAUTION: This is a new project, of alpha status. There may be future
incompatible changes ahead.

== Testing

This library is tested with the official
https://github.com/json-schema-org/JSON-Schema-Test-Suite[JSON-Schema-Test-Suite].

All 444 non-optional tests currently pass.

== Alternative implementations

* https://github.com/niquola/json-schema.clj
