= JSON Schema for Clojure(Script)

Almost all Clojure implementations of https://json-schema.org/[json
schema validators] wrap Java libraries. This is generally a good idea.

However, there are some reasons why a _native_ Clojure implementation
can be useful:

* Java libraries compile jsonschema to object graphs, making them
  inaccessible to many of the data functions in the Clojure core
  library.

* On the front-end, it can be painful to have to convert Clojure data
  to JavaScript objects simply for the purposes of calling a
  jsonschema validation such as
  https://github.com/epoberezkin/ajv[Ajv].

* Extensibility: jsonschema is designed to be extended with additional
  vocabularies. Clojure has some nice open-for-extension mechanisms.

== Scope

This library implements JSON Schema 'draft7'
(draft-handrews-json-schema-validation-01).

== Status

This is a new project.

440/444 validation tests currently pass (all except for `if`, `then`
and `else`) which have not yet been implemented.

Alpha status: changes may break compatibility. Use with caution.



== Testing

This library is tested with the official
https://github.com/json-schema-org/JSON-Schema-Test-Suite[JSON-Schema-Test-Suite].


== Alternative implementations

* https://github.com/niquola/json-schema.clj
